// nf_questions.js — Number Fortress question bank
// t = topic, d = difficulty (1 easy → 5 hard), q = question, o = options, a = index of correct option

export const TOPICS = {
  seq: "Number sequences",
  math: "Mental math",
  logic: "Logic & deduction",
  ana: "Analogies",
  odd: "Odd one out",
  prob: "Probability",
  spat: "Spatial",
  rid: "Riddles",
  code: "Codes & patterns",
};

export const QUESTIONS = [
  /* ---------------- Number sequences ---------------- */
  { t: "seq", d: 1, q: "2, 4, 8, 16, … ?", o: ["24", "32", "30", "34"], a: 1 },
  { t: "seq", d: 1, q: "1, 1, 2, 3, 5, 8, … ?", o: ["11", "12", "13", "15"], a: 2 },
  { t: "seq", d: 1, q: "3, 6, 12, 24, … ?", o: ["36", "40", "44", "48"], a: 3 },
  { t: "seq", d: 1, q: "1, 4, 9, 16, 25, … ?", o: ["36", "30", "35", "49"], a: 0 },
  { t: "seq", d: 1, q: "81, 27, 9, 3, … ?", o: ["0", "1", "2", "1.5"], a: 1 },
  { t: "seq", d: 1, q: "5, 10, 20, 40, … ?", o: ["60", "70", "80", "100"], a: 2 },
  { t: "seq", d: 2, q: "2, 3, 5, 7, 11, … ?", o: ["12", "13", "14", "15"], a: 1 },
  { t: "seq", d: 2, q: "1, 2, 6, 24, 120, … ?", o: ["620", "640", "720", "840"], a: 2 },
  { t: "seq", d: 2, q: "1, 8, 27, 64, … ?", o: ["100", "125", "128", "144"], a: 1 },
  { t: "seq", d: 2, q: "1, 2, 4, 7, 11, 16, … ?", o: ["20", "21", "22", "23"], a: 2 },
  { t: "seq", d: 2, q: "1, 3, 6, 10, 15, … ?", o: ["18", "20", "21", "24"], a: 2 },
  { t: "seq", d: 2, q: "100, 96, 90, 82, … ?", o: ["74", "72", "70", "76"], a: 1 },
  { t: "seq", d: 3, q: "2, 6, 12, 20, 30, … ?", o: ["40", "42", "44", "46"], a: 1 },
  { t: "seq", d: 3, q: "3, 4, 7, 11, 18, 29, … ?", o: ["43", "45", "47", "49"], a: 2 },
  { t: "seq", d: 3, q: "2, 5, 11, 23, 47, … ?", o: ["93", "94", "95", "96"], a: 2 },
  { t: "seq", d: 3, q: "6, 11, 21, 41, 81, … ?", o: ["121", "141", "161", "162"], a: 2 },
  { t: "seq", d: 4, q: "4, 9, 25, 49, 121, … ?", o: ["144", "169", "196", "225"], a: 1 },
  { t: "seq", d: 4, q: "0, 1, 1, 2, 4, 7, 13, … ?", o: ["20", "22", "24", "26"], a: 2 },

  /* ---------------- Mental math ---------------- */
  { t: "math", d: 1, q: "17 + 28 = ?", o: ["44", "45", "46", "47"], a: 1 },
  { t: "math", d: 1, q: "13 × 7 = ?", o: ["81", "89", "91", "97"], a: 2 },
  { t: "math", d: 1, q: "144 ÷ 12 = ?", o: ["11", "12", "13", "14"], a: 1 },
  { t: "math", d: 1, q: "999 + 47 = ?", o: ["1036", "1046", "1047", "1056"], a: 1 },
  { t: "math", d: 1, q: "84 − 37 = ?", o: ["43", "45", "47", "49"], a: 2 },
  { t: "math", d: 1, q: "35% of 200 = ?", o: ["60", "65", "70", "75"], a: 2 },
  { t: "math", d: 2, q: "15% of 80 = ?", o: ["10", "12", "14", "16"], a: 1 },
  { t: "math", d: 2, q: "25 × 16 = ?", o: ["375", "380", "400", "425"], a: 2 },
  { t: "math", d: 2, q: "7 × 8 × 5 = ?", o: ["270", "280", "290", "300"], a: 1 },
  { t: "math", d: 2, q: "45 × 11 = ?", o: ["485", "495", "505", "515"], a: 1 },
  { t: "math", d: 2, q: "¾ of 220 = ?", o: ["155", "160", "165", "175"], a: 2 },
  { t: "math", d: 2, q: "2¹⁰ = ?", o: ["512", "1000", "1024", "2048"], a: 2 },
  { t: "math", d: 2, q: "√625 = ?", o: ["23", "24", "25", "26"], a: 2 },
  { t: "math", d: 2, q: "240 ÷ 15 = ?", o: ["14", "15", "16", "18"], a: 2 },
  { t: "math", d: 3, q: "12.5% of 96 = ?", o: ["10", "11", "12", "13"], a: 2 },
  { t: "math", d: 3, q: "19 × 21 = ?", o: ["389", "399", "409", "419"], a: 1 },
  { t: "math", d: 3, q: "17² = ?", o: ["279", "283", "289", "299"], a: 2 },
  { t: "math", d: 3, q: "111 × 11 = ?", o: ["1211", "1221", "1231", "1121"], a: 1 },

  /* ---------------- Logic & deduction ---------------- */
  { t: "logic", d: 1, q: "Ali is taller than Sami. Sami is taller than Karim. Who is the shortest?", o: ["Ali", "Sami", "Karim", "Can't tell"], a: 2 },
  { t: "logic", d: 1, q: "In a race, you overtake the runner in 2nd place. What position are you in now?", o: ["1st", "2nd", "3rd", "Can't tell"], a: 1 },
  { t: "logic", d: 1, q: "A farmer has 17 sheep. All but 9 die. How many are left?", o: ["8", "9", "17", "0"], a: 1 },
  { t: "logic", d: 1, q: "Which is heavier: a kilo of steel or a kilo of feathers?", o: ["Steel", "Feathers", "They're equal", "Depends on volume"], a: 2 },
  { t: "logic", d: 1, q: "Ahmed's father has four sons: North, South, East, and…?", o: ["West", "Ahmed", "Cannot be known", "The father"], a: 1 },
  { t: "logic", d: 2, q: "If it rains, the street gets wet. The street is wet. What can we conclude?", o: ["It rained", "It didn't rain", "It might have rained, or something else made it wet", "The street is always wet"], a: 2 },
  { t: "logic", d: 2, q: "A is B's brother. B is C's mother. What is A to C?", o: ["Father", "Uncle", "Grandfather", "Cousin"], a: 1 },
  { t: "logic", d: 2, q: "A lily patch doubles in size every day and covers the lake on day 48. On which day was it half covered?", o: ["Day 24", "Day 46", "Day 47", "Day 44"], a: 2 },
  { t: "logic", d: 2, q: "All Zorks are red. Nothing red is round. Therefore…", o: ["Some Zorks are round", "No Zork is round", "All round things are Zorks", "Nothing can be concluded"], a: 1 },
  { t: "logic", d: 3, q: "Five people each shake hands with everyone else exactly once. How many handshakes happen?", o: ["5", "10", "20", "25"], a: 1 },
  { t: "logic", d: 3, q: "If some Blips are Blops, and all Blops are Bleps, then…", o: ["All Blips are Bleps", "Some Blips are Bleps", "No Blips are Bleps", "All Bleps are Blips"], a: 1 },
  { t: "logic", d: 3, q: "5 machines make 5 items in 5 minutes. How long do 100 machines need to make 100 items?", o: ["100 minutes", "20 minutes", "5 minutes", "1 minute"], a: 2 },
  { t: "logic", d: 3, q: "A bat and a ball cost €1.10 together. The bat costs €1 more than the ball. What does the ball cost?", o: ["€0.10", "€0.05", "€0.15", "€1.00"], a: 1 },
  { t: "logic", d: 3, q: "All roses are flowers. Some flowers fade quickly. Which conclusion is certain?", o: ["Some roses fade quickly", "All roses fade quickly", "No rose fades quickly", "None of these is certain"], a: 3 },
  { t: "logic", d: 4, q: "A clock shows 3:15. What is the angle between the two hands?", o: ["0°", "7.5°", "15°", "30°"], a: 1 },

  /* ---------------- Analogies ---------------- */
  { t: "ana", d: 1, q: "Bird is to fly as fish is to…?", o: ["Water", "Swim", "Scales", "Sea"], a: 1 },
  { t: "ana", d: 1, q: "Book is to read as music is to…?", o: ["Sing", "Play", "Listen", "Dance"], a: 2 },
  { t: "ana", d: 1, q: "Doctor is to hospital as teacher is to…?", o: ["Students", "School", "Books", "Lesson"], a: 1 },
  { t: "ana", d: 1, q: "Hand is to glove as foot is to…?", o: ["Leg", "Toe", "Sock", "Walk"], a: 2 },
  { t: "ana", d: 1, q: "Caterpillar is to butterfly as tadpole is to…?", o: ["Fish", "Frog", "Snake", "Lizard"], a: 1 },
  { t: "ana", d: 1, q: "France is to euro as Japan is to…?", o: ["Yuan", "Won", "Yen", "Dollar"], a: 2 },
  { t: "ana", d: 2, q: "Water is to thirst as food is to…?", o: ["Eating", "Hunger", "Cooking", "Taste"], a: 1 },
  { t: "ana", d: 2, q: "Author is to novel as sculptor is to…?", o: ["Stone", "Chisel", "Statue", "Museum"], a: 2 },
  { t: "ana", d: 2, q: "Seed is to tree as egg is to…?", o: ["Nest", "Shell", "Bird", "Breakfast"], a: 2 },
  { t: "ana", d: 2, q: "Marathon is to stamina as sprint is to…?", o: ["Distance", "Speed", "Track", "Legs"], a: 1 },
  { t: "ana", d: 2, q: "Painter is to brush as surgeon is to…?", o: ["Hospital", "Patient", "Scalpel", "Gloves"], a: 2 },
  { t: "ana", d: 2, q: "Optimist is to hopeful as pessimist is to…?", o: ["Happy", "Gloomy", "Careful", "Quiet"], a: 1 },
  { t: "ana", d: 3, q: "Scarce is to abundant as brave is to…?", o: ["Strong", "Fearless", "Cowardly", "Careful"], a: 2 },

  /* ---------------- Odd one out ---------------- */
  { t: "odd", d: 1, q: "Which doesn't belong: Apple, Banana, Carrot, Mango?", o: ["Apple", "Banana", "Carrot", "Mango"], a: 2 },
  { t: "odd", d: 1, q: "Which doesn't belong: Mercury, Venus, Moon, Mars?", o: ["Mercury", "Venus", "Moon", "Mars"], a: 2 },
  { t: "odd", d: 1, q: "Which doesn't belong: Copper, Iron, Wood, Silver?", o: ["Copper", "Iron", "Wood", "Silver"], a: 2 },
  { t: "odd", d: 1, q: "Which doesn't belong: Paris, London, Egypt, Madrid?", o: ["Paris", "London", "Egypt", "Madrid"], a: 2 },
  { t: "odd", d: 1, q: "Which doesn't belong: 3, 5, 7, 12, 17?", o: ["3", "5", "12", "17"], a: 2 },
  { t: "odd", d: 2, q: "Which doesn't belong: 2, 3, 5, 9, 11?", o: ["2", "3", "9", "11"], a: 2 },
  { t: "odd", d: 2, q: "Which doesn't belong: Square, Triangle, Circle, Rectangle?", o: ["Square", "Triangle", "Circle", "Rectangle"], a: 2 },
  { t: "odd", d: 2, q: "Which doesn't belong: Whale, Shark, Dolphin, Seal?", o: ["Whale", "Shark", "Dolphin", "Seal"], a: 1 },
  { t: "odd", d: 2, q: "Which doesn't belong: Guitar, Violin, Piano, Flute?", o: ["Guitar", "Violin", "Piano", "Flute"], a: 3 },
  { t: "odd", d: 2, q: "Which doesn't belong: Nose, Ear, Eye, Kidney?", o: ["Nose", "Ear", "Eye", "Kidney"], a: 3 },
  { t: "odd", d: 3, q: "Which doesn't belong: 8, 27, 64, 100, 125?", o: ["8", "27", "100", "125"], a: 2 },
  { t: "odd", d: 3, q: "Which doesn't belong: 121, 144, 169, 180, 196?", o: ["121", "144", "180", "196"], a: 2 },
  { t: "odd", d: 3, q: "Which doesn't belong: January, May, June, July, August?", o: ["January", "May", "June", "August"], a: 2 },

  /* ---------------- Probability ---------------- */
  { t: "prob", d: 1, q: "You roll one fair die. Probability of an even number?", o: ["1/6", "1/3", "1/2", "2/3"], a: 2 },
  { t: "prob", d: 1, q: "A bag holds 3 red and 2 blue balls. Probability of drawing red?", o: ["1/2", "2/5", "3/5", "3/4"], a: 2 },
  { t: "prob", d: 2, q: "A fair coin is flipped twice. Probability of two heads?", o: ["1/2", "1/3", "1/4", "3/4"], a: 2 },
  { t: "prob", d: 2, q: "A coin landed heads 5 times in a row. Probability the next flip is heads?", o: ["Less than 1/2", "Exactly 1/2", "More than 1/2", "Impossible to say"], a: 1 },
  { t: "prob", d: 2, q: "Two dice are rolled. Probability the sum is 12?", o: ["1/12", "1/18", "1/36", "1/6"], a: 2 },
  { t: "prob", d: 2, q: "One card is drawn from a standard 52-card deck. Probability it's a king?", o: ["1/52", "1/26", "1/13", "1/4"], a: 2 },
  { t: "prob", d: 3, q: "Two dice are rolled. Probability the sum is 7?", o: ["1/12", "1/6", "1/9", "1/36"], a: 1 },
  { t: "prob", d: 3, q: "A fair coin is flipped twice. Probability of at least one head?", o: ["1/2", "2/3", "3/4", "1/4"], a: 2 },
  { t: "prob", d: 4, q: "A bag holds 4 red and 4 blue balls. You draw 2 without replacement. Probability both are red?", o: ["1/4", "3/14", "1/2", "2/7"], a: 1 },
  { t: "prob", d: 5, q: "Monty Hall: 3 doors, you pick one, host opens a losing door and offers a switch. Probability you win if you switch?", o: ["1/3", "1/2", "2/3", "3/4"], a: 2 },

  /* ---------------- Spatial ---------------- */
  { t: "spat", d: 1, q: "How many faces does a cube have?", o: ["4", "6", "8", "12"], a: 1 },
  { t: "spat", d: 2, q: "How many edges does a cube have?", o: ["6", "8", "10", "12"], a: 3 },
  { t: "spat", d: 2, q: "How many corners (vertices) does a cube have?", o: ["6", "8", "10", "12"], a: 1 },
  { t: "spat", d: 2, q: "Fold a sheet of paper in half 3 times, then unfold. How many sections?", o: ["6", "8", "12", "16"], a: 1 },
  { t: "spat", d: 2, q: "On a standard die, opposite faces sum to 7. What is opposite the 3?", o: ["2", "4", "5", "6"], a: 1 },
  { t: "spat", d: 3, q: "A clock in a mirror appears to show 3:00. What's the real time?", o: ["3:00", "6:00", "9:00", "12:00"], a: 2 },
  { t: "spat", d: 3, q: "Rotate the letter N by 90° clockwise. It most resembles…?", o: ["The letter S", "The letter Z", "The letter M", "The letter W"], a: 1 },
  { t: "spat", d: 4, q: "What's the minimum number of straight cuts to divide a round cake into 8 equal pieces?", o: ["3", "4", "7", "8"], a: 0 },
  { t: "spat", d: 4, q: "How many squares of ALL sizes are on a 3×3 grid?", o: ["9", "12", "14", "17"], a: 2 },
  { t: "spat", d: 4, q: "A cube is painted outside, then cut into 27 small cubes. How many small cubes have NO paint?", o: ["0", "1", "3", "6"], a: 1 },
  { t: "spat", d: 5, q: "Same painted cube cut into 27: how many small cubes have paint on EXACTLY 2 faces?", o: ["6", "8", "12", "24"], a: 2 },

  /* ---------------- Riddles ---------------- */
  { t: "rid", d: 1, q: "What has keys but can't open locks?", o: ["A map", "A piano", "A code", "A locksmith"], a: 1 },
  { t: "rid", d: 1, q: "What gets wetter the more it dries?", o: ["A sponge", "Rain", "A towel", "Soap"], a: 2 },
  { t: "rid", d: 1, q: "Which month has 28 days?", o: ["February only", "All of them", "None", "Leap years only"], a: 1 },
  { t: "rid", d: 1, q: "What has hands but cannot clap?", o: ["A statue", "A clock", "A glove", "A robot"], a: 1 },
  { t: "rid", d: 2, q: "The more you take, the more you leave behind. What are they?", o: ["Memories", "Photos", "Footsteps", "Breaths"], a: 2 },
  { t: "rid", d: 2, q: "I speak without a mouth and hear without ears. What am I?", o: ["A phone", "An echo", "The wind", "A thought"], a: 1 },
  { t: "rid", d: 2, q: "What has a neck but no head?", o: ["A shirt", "A guitar", "A bottle", "A giraffe statue"], a: 2 },
  { t: "rid", d: 2, q: "What is tomorrow's yesterday?", o: ["Yesterday", "Today", "Tomorrow", "Two days ago"], a: 1 },
  { t: "rid", d: 3, q: "What can travel around the world while staying in a corner?", o: ["A spider", "A stamp", "A satellite", "A shadow"], a: 1 },
  { t: "rid", d: 3, q: "What breaks the moment you say its name?", o: ["A promise", "Glass", "Silence", "A secret"], a: 2 },
  { t: "rid", d: 3, q: "Two fathers and two sons share 3 apples, and each person gets exactly one. How?", o: ["One apple is cut", "They are grandfather, father and son", "One person gets none", "It's impossible"], a: 1 },
  { t: "rid", d: 4, q: "Forward I am heavy, but backward I am not. What am I?", o: ["A truck", "The word 'ton'", "An anchor", "The word 'stone'"], a: 1 },

  /* ---------------- Codes & patterns ---------------- */
  { t: "code", d: 2, q: "If A=1, B=2, C=3… what is the total value of 'CAB'?", o: ["5", "6", "7", "8"], a: 1 },
  { t: "code", d: 2, q: "Binary 101 equals which decimal number?", o: ["3", "4", "5", "6"], a: 2 },
  { t: "code", d: 2, q: "Continue the pattern: Z, X, V, T, …?", o: ["S", "R", "Q", "P"], a: 1 },
  { t: "code", d: 3, q: "If CODE is written as DPEF, how is GAME written?", o: ["HBNF", "HBMF", "FZLD", "HCNF"], a: 0 },
  { t: "code", d: 3, q: "If MOON becomes NPPO, STAR becomes…?", o: ["TUBS", "TUAS", "SUBT", "TSBU"], a: 0 },
  { t: "code", d: 3, q: "If A=1, B=2… and RED = 27, then BLUE = ?", o: ["38", "39", "40", "42"], a: 2 },
  { t: "code", d: 3, q: "Continue: A, B, D, G, K, …?", o: ["N", "O", "P", "Q"], a: 2 },
  { t: "code", d: 3, q: "If 2→6, 3→12, 4→20, 5→30, then 6→?", o: ["36", "40", "42", "48"], a: 2 },
  { t: "code", d: 4, q: "What letter comes next: A, C, F, J, O, …?", o: ["S", "T", "U", "V"], a: 2 },
  { t: "code", d: 4, q: "Continue: O, T, T, F, F, S, S, …?", o: ["T", "E", "N", "O"], a: 1 },
];
